<?php
session_start();
require_once dirname(__DIR__) . '/includes/auth.php';
require_once dirname(__DIR__) . '/config/database.php';

requireRole('Election Commissioner');

// For now, we'll use a simple HTML to PDF approach using DomPDF
// In a production environment, you might want to use libraries like TCPDF or mPDF

$type = $_GET['type'] ?? '';
$election_id = (int)($_GET['election_id'] ?? 0);
$year = (int)($_GET['year'] ?? date('Y'));

if (!$type) {
    die('Report type is required.');
}

// Simple HTML to PDF conversion function
function generateHTMLReport($title, $content) {
    $html = "
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset='UTF-8'>
        <title>{$title}</title>
        <style>
            body { font-family: Arial, sans-serif; margin: 20px; }
            .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #333; padding-bottom: 10px; }
            .section { margin-bottom: 20px; }
            .section h3 { color: #333; border-bottom: 1px solid #ccc; padding-bottom: 5px; }
            table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
            th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
            th { background-color: #f2f2f2; font-weight: bold; }
            .winner { background-color: #d4edda; }
            .stats { background-color: #f8f9fa; padding: 15px; border-radius: 5px; }
            .footer { margin-top: 30px; text-align: center; font-size: 12px; color: #666; }
        </style>
    </head>
    <body>
        <div class='header'>
            <h1>{$title}</h1>
            <p>Generated on: " . date('F j, Y \a\t g:i A') . "</p>
        </div>
        {$content}
        <div class='footer'>
            <p>This report was generated by the Election Management System</p>
            <p>© " . date('Y') . " - Official Election Results</p>
        </div>
    </body>
    </html>";
    
    return $html;
}

try {
    switch ($type) {
        case 'class':
            if (!$election_id) {
                throw new Exception('Election ID is required for class reports.');
            }
            
            // Get class election details
            $stmt = $pdo->prepare("
                SELECT e.*, et.election_type_name, c.class_name, d.department_name
                FROM elections e
                JOIN election_types et ON e.election_type_id = et.election_type_id
                LEFT JOIN classes c ON e.class_id = c.class_id
                LEFT JOIN departments d ON c.department_id = d.department_id
                WHERE e.election_id = ? AND et.election_type_name = 'class'
            ");
            $stmt->execute([$election_id]);
            $election = $stmt->fetch();
            
            if (!$election) {
                throw new Exception('Class election not found.');
            }
            
            $content = generateClassReportContent($pdo, $election);
            $title = "Class Election Report - {$election['class_name']} ({$election['election_year']})";
            break;
            
        case 'union':
            if (!$election_id) {
                throw new Exception('Election ID is required for union reports.');
            }
            
            // Get union election details
            $stmt = $pdo->prepare("
                SELECT e.*, et.election_type_name
                FROM elections e
                JOIN election_types et ON e.election_type_id = et.election_type_id
                WHERE e.election_id = ? AND et.election_type_name = 'union'
            ");
            $stmt->execute([$election_id]);
            $election = $stmt->fetch();
            
            if (!$election) {
                throw new Exception('Union election not found.');
            }
            
            $content = generateUnionReportContent($pdo, $election);
            $title = "Union Election Report - {$election['election_year']}";
            break;
            
        case 'all_class':
            if (!$year) {
                throw new Exception('Year is required for all class reports.');
            }
            
            // Get all class elections for the year
            $stmt = $pdo->prepare("
                SELECT e.*, et.election_type_name, c.class_name, d.department_name
                FROM elections e
                JOIN election_types et ON e.election_type_id = et.election_type_id
                LEFT JOIN classes c ON e.class_id = c.class_id
                LEFT JOIN departments d ON c.department_id = d.department_id
                WHERE e.election_year = ? AND et.election_type_name = 'class'
                ORDER BY c.class_name
            ");
            $stmt->execute([$year]);
            $class_elections = $stmt->fetchAll();
            
            if (empty($class_elections)) {
                throw new Exception('No class elections found for the specified year.');
            }
            
            $content = generateAllClassReportsContent($pdo, $class_elections, $year);
            $title = "All Class Election Reports - {$year}";
            break;
            
        case 'all_union':
            if (!$year) {
                throw new Exception('Year is required for all union reports.');
            }
            
            // Get all union elections for the year
            $stmt = $pdo->prepare("
                SELECT e.*, et.election_type_name
                FROM elections e
                JOIN election_types et ON e.election_type_id = et.election_type_id
                WHERE e.election_year = ? AND et.election_type_name = 'union'
                ORDER BY e.election_year
            ");
            $stmt->execute([$year]);
            $union_elections = $stmt->fetchAll();
            
            if (empty($union_elections)) {
                throw new Exception('No union elections found for the specified year.');
            }
            
            $content = generateAllUnionReportsContent($pdo, $union_elections, $year);
            $title = "All Union Election Reports - {$year}";
            break;
            
        default:
            throw new Exception('Invalid report type.');
    }
    
    $html = generateHTMLReport($title, $content);
    
    // Set headers for HTML display (can be printed as PDF)
    header('Content-Type: text/html; charset=UTF-8');

    // Add print styles and functionality
    $html = str_replace('</head>', '
        <style media="print">
            body { margin: 0; }
            .no-print { display: none; }
        </style>
        <script>
            function printReport() {
                window.print();
            }
            function downloadPDF() {
                // Simple approach - use browser print to PDF
                window.print();
            }
        </script>
    </head>', $html);

    // Add print button
    $print_button = '
        <div class="no-print" style="position: fixed; top: 10px; right: 10px; z-index: 1000;">
            <button onclick="printReport()" style="padding: 10px 20px; background: #007bff; color: white; border: none; border-radius: 5px; cursor: pointer; margin-right: 10px;">
                🖨️ Print/Save as PDF
            </button>
            <button onclick="window.close()" style="padding: 10px 20px; background: #6c757d; color: white; border: none; border-radius: 5px; cursor: pointer;">
                ✖️ Close
            </button>
        </div>
    ';

    $html = str_replace('<body>', '<body>' . $print_button, $html);

    echo $html;
    
} catch (Exception $e) {
    die('Error generating report: ' . $e->getMessage());
}

function generateClassReportContent($pdo, $election) {
    $content = "<div class='section'>";
    $content .= "<h3>Election Information</h3>";
    $content .= "<div class='stats'>";
    $content .= "<p><strong>Class:</strong> {$election['class_name']}</p>";
    $content .= "<p><strong>Department:</strong> {$election['department_name']}</p>";
    $content .= "<p><strong>Election Year:</strong> {$election['election_year']}</p>";
    $content .= "<p><strong>Status:</strong> " . ucfirst(str_replace('_', ' ', $election['voting_status'])) . "</p>";
    $content .= "</div></div>";
    
    // Get voting statistics
    $stmt = $pdo->prepare("
        SELECT COUNT(*) as total_students
        FROM users u
        JOIN roles r ON u.role_id = r.role_id
        WHERE u.class_id = ? AND r.role_name = 'Student'
    ");
    $stmt->execute([$election['class_id']]);
    $total_students = $stmt->fetchColumn();
    
    $stmt = $pdo->prepare("
        SELECT COUNT(DISTINCT voter_id) as voted_students
        FROM votes
        WHERE election_id = ?
    ");
    $stmt->execute([$election['election_id']]);
    $voted_students = $stmt->fetchColumn();
    
    $content .= "<div class='section'>";
    $content .= "<h3>Voting Statistics</h3>";
    $content .= "<div class='stats'>";
    $content .= "<p><strong>Total Students:</strong> {$total_students}</p>";
    $content .= "<p><strong>Participation Rate:</strong> " . ($total_students > 0 ? round(($voted_students / $total_students) * 100, 1) : 0) . "%</p>";
    $content .= "</div></div>";
    
    // Generate results for each gender category
    $gender_categories = [
        'girls' => ['name' => 'Girls Representative', 'gender' => 'F'],
        'boys' => ['name' => 'Boys Representative', 'gender' => 'M']
    ];
    
    foreach ($gender_categories as $category => $info) {
        $content .= "<div class='section'>";
        $content .= "<h3>{$info['name']} Results</h3>";
        
        // Get candidates and results
        $stmt = $pdo->prepare("
            SELECT
                c.candidate_id,
                u.fname,
                u.lname,
                u.roll_number,
                COUNT(v.vote_id) as vote_count
            FROM candidates c
            JOIN users u ON c.user_id = u.user_id
            LEFT JOIN votes v ON c.candidate_id = v.candidate_id AND v.election_id = ? AND v.gender_category = ?
            WHERE c.election_id = ? AND c.is_approved = 'approved' AND u.gender = ?
            GROUP BY c.candidate_id
            ORDER BY vote_count DESC, u.fname, u.lname
        ");
        $stmt->execute([$election['election_id'], $category, $election['election_id'], $info['gender']]);
        $results = $stmt->fetchAll();
        
        // Get nil votes
        $stmt = $pdo->prepare("
            SELECT COUNT(*) as nil_votes
            FROM votes v
            WHERE v.election_id = ? AND v.gender_category = ? AND v.candidate_id IS NULL
        ");
        $stmt->execute([$election['election_id'], $category]);
        $nil_votes = $stmt->fetchColumn();
        
        $total_votes = array_sum(array_column($results, 'vote_count')) + $nil_votes;
        
        $content .= "<table>";
        $content .= "<tr><th>Rank</th><th>Candidate</th><th>Roll Number</th><th>Votes</th><th>Percentage</th><th>Status</th></tr>";
        
        $rank = 1;
        foreach ($results as $result) {
            $percentage = $total_votes > 0 ? round(($result['vote_count'] / $total_votes) * 100, 1) : 0;
            $is_winner = ($rank === 1 && $result['vote_count'] > 0);
            $row_class = $is_winner ? " class='winner'" : "";
            
            $content .= "<tr{$row_class}>";
            $content .= "<td>{$rank}</td>";
            $content .= "<td>{$result['fname']} {$result['lname']}</td>";
            $content .= "<td>{$result['roll_number']}</td>";
            $content .= "<td>{$result['vote_count']}</td>";
            $content .= "<td>{$percentage}%</td>";
            $content .= "<td>" . ($is_winner ? "Winner" : "Candidate") . "</td>";
            $content .= "</tr>";
            $rank++;
        }
        
        if ($nil_votes > 0) {
            $nil_percentage = $total_votes > 0 ? round(($nil_votes / $total_votes) * 100, 1) : 0;
            $content .= "<tr>";
            $content .= "<td>-</td>";
            $content .= "<td><em>Nil Votes</em></td>";
            $content .= "<td>-</td>";
            $content .= "<td>{$nil_votes}</td>";
            $content .= "<td>{$nil_percentage}%</td>";
            $content .= "<td>Nil</td>";
            $content .= "</tr>";
        }
        
        $content .= "</table>";
        $content .= "<p><strong>Total Votes for {$info['name']}:</strong> {$total_votes}</p>";
        $content .= "</div>";
    }
    
    return $content;
}

function generateUnionReportContent($pdo, $election) {
    $content = "<div class='section'>";
    $content .= "<h3>Election Information</h3>";
    $content .= "<div class='stats'>";
    $content .= "<p><strong>Election Year:</strong> {$election['election_year']}</p>";
    $content .= "<p><strong>Status:</strong> " . ucfirst(str_replace('_', ' ', $election['voting_status'])) . "</p>";
    $content .= "</div></div>";
    
    // Get union positions
    $stmt = $pdo->prepare("
        SELECT position_id, position_name, voting_order
        FROM positions
        WHERE election_type_id = 2
        ORDER BY voting_order
    ");
    $stmt->execute();
    $positions = $stmt->fetchAll();
    
    foreach ($positions as $position) {
        $content .= "<div class='section'>";
        $content .= "<h3>{$position['position_name']} Results</h3>";
        
        // Get candidates and results for this position
        $stmt = $pdo->prepare("
            SELECT
                c.candidate_id,
                u.fname,
                u.lname,
                u.roll_number,
                cl.class_name,
                d.department_name,
                COUNT(v.vote_id) as vote_count
            FROM candidates c
            JOIN users u ON c.user_id = u.user_id
            JOIN classes cl ON u.class_id = cl.class_id
            JOIN departments d ON cl.department_id = d.department_id
            LEFT JOIN votes v ON c.candidate_id = v.candidate_id AND v.election_id = ?
            WHERE c.position_id = ? AND c.election_id = ? AND c.is_approved = 'approved'
            GROUP BY c.candidate_id
            ORDER BY vote_count DESC, u.fname, u.lname
        ");
        $stmt->execute([$election['election_id'], $position['position_id'], $election['election_id']]);
        $results = $stmt->fetchAll();
        
        // Get nil votes for this position
        $stmt = $pdo->prepare("
            SELECT COUNT(*) as nil_votes
            FROM votes v
            WHERE v.election_id = ? AND v.position_id = ? AND v.candidate_id IS NULL
        ");
        $stmt->execute([$election['election_id'], $position['position_id']]);
        $nil_votes = $stmt->fetchColumn();
        
        $total_votes = array_sum(array_column($results, 'vote_count')) + $nil_votes;
        
        $content .= "<table>";
        $content .= "<tr><th>Rank</th><th>Candidate</th><th>Class</th><th>Votes</th><th>Percentage</th><th>Status</th></tr>";
        
        $rank = 1;
        foreach ($results as $result) {
            $percentage = $total_votes > 0 ? round(($result['vote_count'] / $total_votes) * 100, 1) : 0;
            $is_winner = ($rank === 1 && $result['vote_count'] > 0);
            $row_class = $is_winner ? " class='winner'" : "";
            
            $content .= "<tr{$row_class}>";
            $content .= "<td>{$rank}</td>";
            $content .= "<td>{$result['fname']} {$result['lname']} ({$result['roll_number']})</td>";
            $content .= "<td>{$result['class_name']}, {$result['department_name']}</td>";
            $content .= "<td>{$result['vote_count']}</td>";
            $content .= "<td>{$percentage}%</td>";
            $content .= "<td>" . ($is_winner ? "Winner" : "Candidate") . "</td>";
            $content .= "</tr>";
            $rank++;
        }
        
        if ($nil_votes > 0) {
            $nil_percentage = $total_votes > 0 ? round(($nil_votes / $total_votes) * 100, 1) : 0;
            $content .= "<tr>";
            $content .= "<td>-</td>";
            $content .= "<td><em>Nil Votes</em></td>";
            $content .= "<td>-</td>";
            $content .= "<td>{$nil_votes}</td>";
            $content .= "<td>{$nil_percentage}%</td>";
            $content .= "<td>Nil</td>";
            $content .= "</tr>";
        }
        
        $content .= "</table>";
        $content .= "<p><strong>Total Votes for {$position['position_name']}:</strong> {$total_votes}</p>";
        $content .= "</div>";
    }
    
    return $content;
}

function generateAllClassReportsContent($pdo, $class_elections, $year) {
    $content = "<div class='section'>";
    $content .= "<h3>Summary</h3>";
    $content .= "<div class='stats'>";
    $content .= "<p><strong>Election Year:</strong> {$year}</p>";
    $content .= "<p><strong>Total Class Elections:</strong> " . count($class_elections) . "</p>";
    $content .= "</div></div>";
    
    foreach ($class_elections as $election) {
        $content .= "<div style='page-break-before: always;'>";
        $content .= generateClassReportContent($pdo, $election);
        $content .= "</div>";
    }
    
    return $content;
}

function generateAllUnionReportsContent($pdo, $union_elections, $year) {
    $content = "<div class='section'>";
    $content .= "<h3>Summary</h3>";
    $content .= "<div class='stats'>";
    $content .= "<p><strong>Election Year:</strong> {$year}</p>";
    $content .= "<p><strong>Total Union Elections:</strong> " . count($union_elections) . "</p>";
    $content .= "</div></div>";
    
    foreach ($union_elections as $election) {
        $content .= "<div style='page-break-before: always;'>";
        $content .= generateUnionReportContent($pdo, $election);
        $content .= "</div>";
    }
    
    return $content;
}

?>
